#ifndef TZN_LIMITS_H
#define TZN_LIMITS_H

#define TZN_REGISTER_COUNT 9
#define TZN_SPECIAL_REGISTER_COUNT 3
#define TZN_GENERAL_REGISTER_COUNT (TZN_REGISTER_COUNT - TZN_SPECIAL_REGISTER_COUNT)
#define TZN_MEMORY_BYTES 65535

#define TZN_MEMORY_RESERVED_START 0x0000
#define TZN_MEMORY_DEVICES_START TZN_MEMORY_RESERVED_START
#define TZN_MEMORY_DEVICES_END 0x001F
#define TZN_MEMORY_RESERVED_END 0x00FF
#define TZN_MEMORY_RAM_START 0x0100
#define TZN_MEMORY_RAM_END 0xFFFF

#endif
